### ISSUE TITLE
GitHub releaseでバイナリを配布できるようにする

### ISSUE THREAD

**Issue by sheepla** [sheepla/fzwiki#3]

**Comment by jiro4989** [comment]
この辺の設定が参考になるかもです
https://github.com/jiro4989/slotchmod/blob/master/.github/workflows/release.yml

**Comment by sheepla** [comment]
おぉ 参考にさせていただきます！

**Comment by sheepla** [comment]
https://github.com/sheepla/fzwiki/commit/e0c2c6d3bfc318f19dd77e50d259fa0294acf3fa release.yml を追加

**Comment by sheepla** [comment]
リリースできました！

https://github.com/sheepla/fzwiki/releases/tag/v0.0.2-alpha
